### ISSUE TITLE
[BUG] Unable to open blank issues

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/.github#26]
### Describe the bug

Blank issue cannot be created. On the "New Issue" page there is an option for "(maintainers only) - Blank issue". It links to https://github.com/nebari-dev/nebari/issues/new/. However this redirects to https://github.com/nebari-dev/nebari/issues/new/choose, i.e. our starting point. Thus, it is currently impossible to open an issue without using a template.

### Expected behavior

Being able to open blank issues

### OS and architecture in which you are running Nebari

GH

### How to Reproduce the problem?

Click the links I provided above

### Compute environment

None

**Comment by pavithraes** [comment]
@pmeier Thanks for opening this issue.

> On the "New Issue" page there is an option for "(maintainers only) - Blank issue". It links to [nebari-dev/nebari/issues/new](https://github.com/nebari-dev/nebari/issues/new/). However this redirects to [nebari-dev/nebari/issues/new/choose](https://github.com/nebari-dev/nebari/issues/new/choose), i.e. our starting point. Thus, it is currently impossible to open an issue without using a template.

As someone in the maintainer group, I'm able to create a blank issue with that link.

Not allowing everyone to open blank issues is a deliberate choice, to encourage folks to add necessary details and context while creating new issues. Ref: https://github.com/nebari-dev/.github/blob/8e0ae707b0fa09a292e66e7f439db0d42e2e2878/.github/ISSUE_TEMPLATE/config.yml#L1

Does this help?

**Comment by pmeier** [comment]
If its deliberate, than we can close this one. 

I personally feel the issue templates create more noise than they remove. For example nebari-dev/nebari#1716. The unfilled sections are as long as the whole report and stuff like

> ### Expected behavior
>
> If we provide such an option it should work.

does not add anything.
